### ISSUE TITLE
Add Less-like jumping shortcuts

### ISSUE THREAD

**Issue by ketozhang** [Textualize/toolong#40]
See `less --help`

I've no idea what are the most popular ones people use. For me the one I cannot do without is `g` and `G` for jumping to first and last line of file (respectively)

**Comment by gennaro-tedesco** [comment]
A more general approach to this could be to provide configurable mappings (not sure how easy it is to provide): generally this seems to be a common request for the Textualize applications, see [here](https://github.com/Textualize/frogmouth/issues/14) and [here](https://github.com/Textualize/frogmouth/issues/10) for similar issues on `frogmouth`. 

A specific case is also the usage of Ctrl-C to exit: in some terminal emulators such combination may close the entire emulator application rather than only quitting the app. For instance `q` to exit is a `less`-like choice that I presume most people already automatically reach for, or `g/G` as mentioned above (and `n/N` to browse the next search result).

**Comment by willmcgugan** [comment]
Added a number of additional keys to 1.5.0

**Comment by gennaro-tedesco** [comment]
As per [this commit](https://github.com/Textualize/toolong/commit/aaa3aa2888d2d0db9f22fb72ffc7891191db5f30#diff-c76de0e8c447cc6ee3c36bbe9e9bb343200be9da0939a8c6569c8bbb6a6e6f52) shouldn't it be, instead, 
```
Binding("home,g", "scroll_home", "Scroll Home", show=False)
Binding("end,G", "scroll_end", "Scroll End", show=False)
```
instead?
